// The name of every route. Navigation goes by these names, never by path.
export const ROUTE_NAMES = {
  splash: 'splash',
  welcome: 'welcome',
  signIn: 'sign-in',
  createAccount: 'create-account',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  setupPlan: 'setup-plan',
  setupIntro: 'setup-intro',
  setupSpecies: 'setup-species',
  setupEnvironment: 'setup-environment',
  setupWaterRanges: 'setup-water-ranges',
  setupDimensions: 'setup-dimensions',
  setupFingerlings: 'setup-fingerlings',
  setupStockingResult: 'setup-stocking-result',
  setupReview: 'setup-review',
  setupSuccess: 'setup-success',
  home: 'home',
  cultivations: 'cultivations',
  cultivationDetail: 'cultivation-detail',
  cultivationTasks: 'cultivation-tasks',
  cultivationGrowth: 'cultivation-growth',
  cultivationRecords: 'cultivation-records',
  cultivationHarvest: 'cultivation-harvest',
  cultivationWaterSafety: 'cultivation-water-safety',
  feedGuide: 'feed-guide',
  marketplace: 'marketplace',
  productDetail: 'product-detail',
  cart: 'cart',
  checkout: 'checkout',
  orders: 'orders',
  orderDetail: 'order-detail',
  orderTracking: 'order-tracking',
  notifications: 'notifications',
  profile: 'profile',
  plans: 'plans',
  offline: 'offline',
  notFound: 'not-found',
} as const

export type RouteName = (typeof ROUTE_NAMES)[keyof typeof ROUTE_NAMES]
